# Importing Libraries

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing Dataset

In [9]:
dataset = pd.read_csv("/home/akanksha/Downloads/Social_Network_Ads.csv")
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

# Spliting Dataset into Training and Test Set

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

# Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [12]:
print(x_train)

[[-0.80330081 -1.19121795]
 [ 0.75697997 -1.36859801]
 [ 0.85449752  1.43991958]
 [-0.51074816 -1.48685138]
 [-1.48592365  0.37563923]
 [-1.19337101  0.55301929]
 [ 1.04953262 -1.04340124]
 [-0.21819552 -0.30431766]
 [ 0.95201507 -1.33903467]
 [-1.09585346 -1.07296458]
 [-0.51074816  1.97205975]
 [ 2.21974321 -1.0138379 ]
 [ 1.43960282 -1.39816136]
 [ 0.07435713 -0.39300769]
 [-1.19337101  0.64170932]
 [ 2.02470811 -0.89558452]
 [ 1.14705017  0.58258263]
 [-0.02316042  0.2869492 ]
 [-0.21819552  0.25738586]
 [-0.31571307 -0.74776781]
 [-1.68095875 -0.57038775]
 [ 0.85449752  0.58258263]
 [-0.60826571 -1.0138379 ]
 [ 0.95201507 -1.13209127]
 [-0.21819552 -0.54082441]
 [ 0.17187468  0.81908937]
 [-0.41323061  1.32166621]
 [ 1.14705017  0.52345594]
 [ 0.75697997  0.31651254]
 [ 0.65946243 -0.86602118]
 [ 0.36690978 -0.27475432]
 [ 0.46442733 -0.45213438]
 [-0.21819552  0.13913248]
 [ 0.36690978  0.10956914]
 [-0.99833591  0.81908937]
 [-0.70578326  1.41035623]
 [ 0.36690978 -0.48169772]
 

In [13]:
print(x_test)

[[-0.12067797 -1.04340124]
 [ 0.17187468 -0.21562763]
 [-0.12067797  1.46948292]
 [ 0.17187468  1.58773629]
 [-1.09585346  1.46948292]
 [ 0.07435713 -0.09737426]
 [-1.68095875 -0.95471121]
 [ 1.14705017  0.61214597]
 [-0.60826571 -1.48685138]
 [ 1.04953262  2.14943981]
 [-0.31571307  0.10956914]
 [ 0.17187468  0.13913248]
 [-0.21819552  0.10956914]
 [ 1.04953262  1.85380638]
 [ 1.53712037  0.40520257]
 [ 1.82967301  1.91293307]
 [ 2.21974321  0.43476591]
 [-0.99833591 -0.30431766]
 [-0.90081836  0.55301929]
 [ 2.21974321  0.99646943]
 [ 0.26939223  0.19825917]
 [ 1.24456772  0.58258263]
 [ 0.65946243  2.09031313]
 [ 0.95201507 -0.74776781]
 [ 0.75697997 -1.25034464]
 [-1.09585346 -1.57554141]
 [ 2.02470811 -0.62951444]
 [ 1.14705017  0.16869583]
 [ 1.53712037 -1.0138379 ]
 [ 1.43960282  1.35122955]
 [ 0.17187468 -0.77733115]
 [-1.7784763   0.22782251]
 [-1.87599385  0.52345594]
 [ 1.92719056  0.16869583]
 [-0.99833591  0.46432926]
 [-0.70578326  0.34607588]
 [-1.48592365 -1.48685138]
 

# Training a Decision Tree model on the Training Set

In [14]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = "entropy", random_state = 1)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=1, splitter='best')

# Predicting New Result

In [15]:
classifier.predict(sc.transform([[30,87000]]))

array([0])

# Predicting Test Set Results

In [16]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


# Making the Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[43  5]
 [ 8 24]]


0.8375