# Importing the Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing the Dataset

In [2]:
dataset = pd.read_csv("/home/akanksha/Downloads/Data (1).csv")
x = dataset.iloc[:,0:-1]
y = dataset.iloc[:,-1]

In [3]:
print(x)

         AT      V       AP     RH
0     14.96  41.76  1024.07  73.17
1     25.18  62.96  1020.04  59.08
2      5.11  39.40  1012.16  92.14
3     20.86  57.32  1010.24  76.64
4     10.82  37.50  1009.23  96.62
...     ...    ...      ...    ...
9563  16.65  49.69  1014.01  91.00
9564  13.19  39.18  1023.67  66.78
9565  31.32  74.33  1012.92  36.48
9566  24.48  69.45  1013.86  62.39
9567  21.60  62.52  1017.23  67.87

[9568 rows x 4 columns]


In [4]:
print(y)

0       463.26
1       444.37
2       488.56
3       446.48
4       473.90
         ...  
9563    460.03
9564    469.62
9565    429.57
9566    435.74
9567    453.28
Name: PE, Length: 9568, dtype: float64


# Splitting the Dataset into Test Set and Training Set

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size = 0.2, random_state =0)

# MULTIPLE LINEAR REGRESSION:

# Training Multiple Linear Regression model on Training Set

In [6]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# Predicting Test Set Result

In [7]:
y_pred_lin_reg = lin_reg.predict(x_test)
np.set_printoptions(precision=2)
y_test = y_test.values.reshape(-1,1)
print(np.concatenate((y_pred_lin_reg.reshape(len(y_pred_lin_reg),1), y_test.reshape(len(y_test),1)),1))

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


# Evaluating Model Performance

In [17]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_lin_reg)

0.9325315554761302

# POLYNOMIAL REGRESSION:

# Training Polynomial Regression model on Training Set

In [8]:
from sklearn.preprocessing import PolynomialFeatures
poly_feat = PolynomialFeatures(degree = 4)
x_train_poly = poly_feat.fit_transform(x_train)

poly_reg = LinearRegression()
poly_reg.fit(x_train_poly, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# Predicting Test Set Result

In [9]:
y_pred_poly_reg = poly_reg.predict(poly_feat.transform(x_test))
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred_poly_reg.reshape(len(y_pred_poly_reg),1), y_test.reshape(len(y_test),1)),1))

[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.67 463.28]]


# Evaluating Model Performance

In [18]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_poly_reg)

0.9458193347147953

# SUPPORT VECTOR REGRESSION:

# Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc_x_train = StandardScaler()
sc_y_train = StandardScaler()
svr_x_train = sc_x_train.fit_transform(x_train)
svr_y_train = sc_y_train.fit_transform(y_train.values.reshape(-1,1))

# Training SVR model on Training Set

In [11]:
from sklearn.svm import SVR
svr_reg = SVR(kernel = 'rbf')
svr_reg.fit(svr_x_train, svr_y_train)

/home/akanksha/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

# Predicting Test Set Result

In [12]:
y_pred_svr_reg = sc_y_train.inverse_transform(svr_reg.predict(sc_x_train.transform(x_test)))
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred_svr_reg.reshape(len(y_pred_svr_reg),1), y_test.reshape(len(y_test),1)),1))

[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]


# Evaluating Model Performance

In [19]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_svr_reg)

0.9480784049986265

# Decision Tree Regression:

# Training Decision Tree Regression model on Training Set

In [13]:
from sklearn.tree import DecisionTreeRegressor
dtr_reg = DecisionTreeRegressor(random_state = 0)
dtr_reg.fit(x_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

# Predicting Test Set Result

In [14]:
y_pred_dtr_reg = dtr_reg.predict(x_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred_dtr_reg.reshape(len(y_pred_dtr_reg), 1), y_test.reshape(len(y_test),1)), 1))

[[431.28 431.23]
 [462.81 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.55 463.28]]


# Evaluating Model Performance

In [20]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_dtr_reg)

0.9226091050550043

# RANDOM FOREST REGRESSION

# Training Decision Tree Regression model on Training Set

In [15]:
from sklearn.ensemble import RandomForestRegressor
rfr_reg = RandomForestRegressor(n_estimators = 10, random_state = 0)
rfr_reg.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

# Predicting New Results

In [16]:
y_pred_rfr_reg = rfr_reg.predict(x_test)
print(np.concatenate((y_pred_rfr_reg.reshape(len(y_pred_rfr_reg),1),y_test.reshape(len(y_test),1)), 1))

[[433.78 431.23]
 [457.99 460.01]
 [463.14 461.14]
 ...
 [470.16 473.26]
 [439.51 438.  ]
 [460.32 463.28]]


# Evaluating Model Performance

In [21]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_rfr_reg)

0.9615980699813017